"""Add game_user Association Table

Revision ID: e9cc40035f52
Revises: 0224405e8b1e
Create Date: 2024-03-14 14:40:46.291599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cc40035f52'
down_revision = '0224405e8b1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
